services:
  redis_test:
    image: redis:7
    command: redis-server --port 6379 --requirepass testpassword
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: testpassword
    networks:
      - test-network
networks:
  test-network:
    driver: bridge
