openapi: 3.0.0
info:
  title: Course Search API
  version: 1.0.0
  description: API documentation for searching courses using Full-Text Search.
paths:
  /search/api-status:
    get:
      tags:
        - Quizz
      summary: Check Quizz APIs status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResStatus'
  /search:
    get:
      tags:
        - Search
      summary: Search for courses based on query parameters
      description: |
        Perform a full-text search on courses using the provided query. Supports pagination through `limit` and `skip` parameters.
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
          description: The search term to query courses.
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            default: 10
          description: The number of results to return. Defaults to 10.
        - in: query
          name: skip
          required: false
          schema:
            type: integer
            default: 0
          description: The number of results to skip for pagination. Defaults to 0.
      responses:
        '200':
          description: Successful search
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ResStatus:
      type: object
      properties:
        status:
          type: string
          example: "OK"
        message:
          type: string
          example: "Quizz APIs are running successfully."

    SearchResponse:
      type: object
      properties:
        message:
          type: string
          example: "Search courses successfully"
        status:
          type: string
          example: "success"
        courses:
          type: array
          items:
            $ref: '#/components/schemas/Course'

    Course:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "95e30afa-020f-463a-907f-142888fa5de1"
        name:
          type: string
          example: "Introduction to Python Programming"
        description:
          type: string
          example: "Learn the fundamentals of Python programming with practical examples and projects."
        teacherId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174003"
        categories:
          type: array
          items:
            type: string
          example: ["Programming", "Python"]
      required:
        - id
        - name
        - description
        - teacherId
        - categories

    Error:
      type: object
      properties:
        error:
          type: string
          example: "Invalid or missing query parameter."
      required:
        - error